<a href="https://colab.research.google.com/github/karsakami/Deep-Learning-with-PyTorch-for-Medical-Image-Analysis/blob/main/CNN%20with%20pytorch/Tensors_basics_and_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CREATING AND RESHAPING TENSORS**

In [1]:
import torch
import numpy as np

Convert normal np array into tensor

In [2]:
# create a np array
arr = np.array([2,3,4,5])

In [3]:
# convertion
x = torch.as_tensor(arr)

In [4]:
# create a new matrix and reshape
arr2 = np.arange(0,16)
arr2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
# change a certain index for value
arr2[3] = 23
arr2

array([ 0,  1,  2, 23,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

The difference between torch.Tensor and torch.tensor its just data type 

In [6]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# you can reshape a torch tensor just like np array 
torch.arange(0,18).reshape(2,9)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [17]:
# func linspace allows us to create linearly spaced values
torch.linspace(0,6,6).reshape(2,3)

tensor([[0.0000, 1.2000, 2.4000],
        [3.6000, 4.8000, 6.0000]])

Uniform distribution

In [18]:
torch.rand(4,3)

tensor([[0.8692, 0.7073, 0.4656],
        [0.6633, 0.5114, 0.7922],
        [0.2555, 0.7795, 0.8672],
        [0.3708, 0.3355, 0.1589]])

Normal distribution

In [19]:
torch.randn(4,3)

tensor([[-0.5110, -0.7841, -0.3142],
        [-1.3540, -0.0308, -1.2165],
        [ 0.6743, -0.3505, -1.2534],
        [-0.4428,  1.1716,  0.3186]])

Random int

In [24]:
torch.randint(0,11 ,(5,5))

tensor([[ 5,  7,  9,  8,  8],
        [ 9,  2,  7,  2,  1],
        [ 0,  4,  5,  0,  1],
        [10,  4,  4, 10,  9],
        [ 4,  1,  3,  3,  5]])

Lets create a random matrix, and then change values by **rand_like** func

In [27]:
x = torch.zeros([2,6])
x

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [30]:
x.shape

torch.Size([2, 6])

We can create matrix with random int, uniform distribution or normal distribution values based on a certain matrix shape

In [31]:
torch.rand_like(x)

tensor([[0.5829, 0.0855, 0.7262, 0.1860, 0.0628, 0.9575],
        [0.6879, 0.3928, 0.6473, 0.6761, 0.8574, 0.4537]])

In [32]:
torch.randn_like(x)

tensor([[-1.1642,  0.8259, -0.0499,  0.5323,  1.2465,  0.1963],
        [ 0.4238,  0.7619,  0.3470,  0.7934,  0.9574, -0.9862]])

Creating random seed for getting same values

In [35]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [43]:
# create 2D tensor
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [46]:
# accesing a tensor certain value
iwant3 = x[1,1]

In [48]:
# remember that we still got a tensor, not a int value
type(iwant3)

torch.Tensor

In [49]:
# slices
x[:,1]

tensor([1, 3, 5])

In [51]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [60]:
# we can also reshape with view function and assign a variable, 
# view is reflecting to the most current data
x = x.view(2,3)
x

tensor([[0, 1, 2],
        [3, 4, 5]])

---
# **Tensors Arithmetic**

###**summation**

In [66]:
a = torch.tensor([23,4,5])
b = torch.tensor([23,4,5])
 
a + b

tensor([46,  8, 10])

In [67]:
# method of sum two variables by function
torch.add(a,b)

tensor([46,  8, 10])

### **multiplication**

In [70]:
a.mul(b)

tensor([529,  16,  25])

or

In [71]:
a * b

tensor([529,  16,  25])

In [72]:
a.mul_(b)
# a = a*b

tensor([529,  16,  25])

---
# **DOT PRODUCT IN PYTORCH**

The size of matrixes must be the same!

In [77]:
a = torch.tensor([1,2,3])
b = torch.tensor([1,2,3])

In [79]:
a.dot(b)

tensor(14)

# **MAT MULTIPLICATION**

Numbers of cols must be same as num of rows! 

In [84]:
a = torch.tensor([[2,3], [2,7],[8,3]])
a.shape

torch.Size([3, 2])

In [92]:
b = torch.tensor([[2,3], [2,7],[8,3],[6,3]]).reshape(2,4)
b.shape

torch.Size([2, 4])

Above we reshaped a matrix, so that the number of columns and rows agree and we can multiply matrices

In [93]:
torch.mm(a,b)

tensor([[28, 15, 22, 23],
        [60, 27, 46, 35],
        [40, 33, 34, 65]])

Second, faster method of matrix multiplication

In [94]:
a @ b

tensor([[28, 15, 22, 23],
        [60, 27, 46, 35],
        [40, 33, 34, 65]])

---
# **EXERCISES**

### 1. Perform standard imports
Import torch and NumPy

In [95]:
import numpy as np
import torch

### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [97]:
np.random.seed(42)

### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [103]:
arr = np.random.randint(0,5,6)
arr

array([2, 4, 4, 1, 2, 2])

### 4. Create a tensor "x" from the array above

In [108]:
x = torch.tensor(arr)
x

tensor([2, 4, 4, 1, 2, 2])

### 5. Change the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [114]:
x = x.type(torch.int64)

# check a type
x.dtype

torch.int64

### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [121]:
x = x.reshape(3,2)
x

tensor([[2, 4],
        [4, 1],
        [2, 2]])

### 7. Return the right-hand column of tensor x

In [122]:
x[:,1]

tensor([4, 1, 2])

### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [123]:
x**2

tensor([[ 4, 16],
        [16,  1],
        [ 4,  4]])

### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [133]:
y = torch.arange(0,6).reshape(2,3)
y

tensor([[0, 1, 2],
        [3, 4, 5]])

### 10. Find the matrix product of x and y

In [132]:
x @ y

tensor([[12, 18, 24],
        [ 3,  8, 13],
        [ 6, 10, 14]])